### ISSUE TITLE
Allow to have multiple entrypoints in `EsBuildConfig` and reflect this in BundleOptions

### ISSUE THREAD

**Issue by ia3andy** [edewit/esbuild-java#5]
```
final BundleOptions options = new BundleOptionsBuilder()
	.addEntryPoint(String name, List<Path> scriptsAndCss) // create a single entry point script for the list of scripts and css
	.addEntryPoint(Path script) // just use that entry point
```

also this way we can remove the global `BundleOptions.bundleName`

Using multiple entrypoints allows to create a smart output with a common bundle, this makes things really flexible:
- index.js load base.js and common.js then somecomponent.js get's loaded by htmx (and works since the common.js has already loaded the lib)
- user can split in different bundles, assets, components, ... without caring about common stuff.

**Comment by edewit** [comment]
Not quite sure if I follow how would this change enable us to get rid of bundleName? Wouldn't the `ddEntryPoint(String bundleName, List<Path> dependencies) ` set `bundleName`?

**Comment by ia3andy** [comment]
@edewit there will be multiple "generated" (or not) entrypoints
so it's not a bundleName but a entrypointName, but yes in the end it's just the name for the generated file.
